### ISSUE TITLE
crash for n_features >10

### ISSUE THREAD

**Issue by chapochn** [sylvchev/mdla#26]
Hello,

Thanks for writing and sharing this code!

in the function:
`multivariate_sparse_encode`
There is at some moment:

`n_nonzero_coefs = max(n_features / 10, 1)`

Which generates a float value for n_features >10, and makes the code crash at:

`decomposition = np.zeros((n_nonzero_coefs, 3)) - 1`
inside _multivariate_OMP.

I imagine one could put something like:
`n_nonzero_coefs = max(int(np.round(n_features / 10)), 1)`

This code generates the crash:
```
import numpy as np
from mdla import MultivariateDictLearning
from mdla import multivariate_sparse_encode
from numpy.linalg import norm

rng_global = np.random.RandomState(0)
n_samples, n_features, n_dims = 10, 11, 3
X = rng_global.randn(n_samples, n_features, n_dims)

n_kernels = 8
dico = MultivariateDictLearning(n_kernels=n_kernels, max_iter=10).fit(X)

```

I understand that setting n_nonzero_coefs by hand is a workaround.

Thanks!

**Comment by sylvchev** [comment]
Thanks for your interest in this project. I will update the code and push a new version on pypi

**Comment by chapochn** [comment]
Thank you for updating!
