### ISSUE TITLE
output of fit in the class MultivariateDictLearning

### ISSUE THREAD

**Issue by chapochn** [sylvchev/mdla#27]
Hi,

I was wondering if there is a reason for not returning the _code_ variable when calling _fit_ in the class _MultivariateDictLearning_, as it is not saved anywhere. Or maybe has it as an internal variable?

Thanks!

**Comment by sylvchev** [comment]
Yes, the code from the fit is an internal variable that is a byproduct obtained during the learning phase. To obtain the code, you could use the transform method, with something like : 
`code = MultivariateDictLearning(n_kernels=n_kernels, max_iter=10).fit(X).transform(X)`

**Comment by chapochn** [comment]
Thanks for explaining! 

So do I understand correctly that then the calculation "multivariate_sparse_encode" would be done twice? And in one case it would call the function "multivariate_dict_learning", which calls "multivariate_sparse_encode", and then when one calls transform(X), it would call "multivariate_sparse_encode" again?

I was thinking that in terms of saving computation time, might be beneficial to have it available already after the first call, if that makes sense?

**Comment by sylvchev** [comment]
These methods (fit, transform, etc) follow the [scikit learn API](https://scikit-learn.org/stable/developers/develop.html). This gives a lot of flexibility to the code that can benefit from all the scikit learn ecosystem (parameter search, model parametrization, evaluation among others). 
My example is indeed really not optimal: a more common example is to have different training and testing data
`mdl = MultivariateDictLearning(n_kernels=n_kernels, max_iter=10).fit(X_train)`
`code = mdl.transform(X_test)`

**Comment by chapochn** [comment]
Ah ok! makes sense, thanks for clarifying!
I believe scikit learn usually has the function `fit_transform` to avoid doing the same calculation twice like in`fit(X).transform(X)`.
In case it becomes an issue in terms of calculation time, I could do a PR at some point.

**Comment by sylvchev** [comment]
Yes, this is very good idea! Feel free to open a PR for this.
